/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sys_prototype_revised;

import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.awt.event.WindowEvent;
import java.awt.Component;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import javax.swing.table.DefaultTableModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowSorter;
import javax.swing.SwingUtilities;
import javax.swing.table.TableModel;
import static sys_prototype_revised.proto_admin_UI.admin_table;

public class FROM_ADMIN_DELETE_PROCESS extends javax.swing.JFrame {

    private static String username;
    private static Connection Dbcon;
    private static List<Map<String, String>> dataList;

    private String sUrl = "jdbc:mysql://localhost:3306/census_system_db";
    private String sUser = "root";
    private String spass = "";
        
        
    private static PreparedStatement pst;
    private static ResultSet result;
    
    
    public FROM_ADMIN_DELETE_PROCESS(List<Map<String, String>> dataList) {
        this.dataList = dataList;
        initComponents();
        SwingUtilities.invokeLater(this::connectLoadData);
        
        /*r_first_name.setText(data.get("FirstName"));
        r_last_name.setText(data.get("LastName"));// Assuming r_last_name is your JTextField for Last Name
        r_address.setText(data.get("Address"));  // Assuming r_address is your JTextField for Address
        r_email_adress.setText(data.get("Email"));
        r_contact.setText(data.get("Contact"));
        r_household_serial.setText(data.get("Household"));
        inCharge.setText(data.get("Worker"));
        r_suffix.setText(data.get("Suffix"));
        r_middle_name.setText(data.get("M_name"));
        r_age.setText(data.get("Age"));
        r_birthdate.setText(data.get("B_date"));
        r_birthplace.setText(data.get("B_place"));
        r_religion.setText(data.get("Religion"));
        r_citizenship.setText(data.get("Citizenship"));
        r_profession.setText(data.get("Profession"));
        r_enumeration_serial.setText(data.get("Enumer"));
        r_building_serial.setText(data.get("Build"));
        r_housing_unit_serial.setText(data.get("Housing"));
        r_sex.setText(data.get("Sex"));
        r_status.setText(data.get("Status"));
        r_attainment.setText(data.get("Attainment"));
        r_listing.setText(data.get("Date_Added"));
        r_entry.setText(data.get("Entry"));*/
        
    }
    
    public void connectLoadData(){
        try{
            connectToDB();
            showTableDb();
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE );
        }
    }
    
    public void connectToDB() throws SQLException{
        String SUrl = "jdbc:mysql://localhost:3306/census_system_db";
        String SUser = "root";
        String Spass = "";
        Dbcon = DriverManager.getConnection(SUrl, SUser, Spass);
    }
    
    private void showError(String message) {
         JOptionPane.showMessageDialog(new FROM_ADMIN_DELETE_PROCESS.JFrame(), message,"Error", JOptionPane.ERROR_MESSAGE);

    }

    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PANEL_3 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        PANEL_3.setBackground(new java.awt.Color(220, 227, 238));
        PANEL_3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PANEL_3.setForeground(new java.awt.Color(247, 247, 247));
        PANEL_3.setPreferredSize(new java.awt.Dimension(850, 500));

        jLabel28.setBackground(new java.awt.Color(247, 247, 247));
        jLabel28.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(40, 40, 40));
        jLabel28.setText("ARE YOU SURE WANT TO DELETE THE SELECTED ENTRY/ENTRIES?");
        jLabel28.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel28.setPreferredSize(new java.awt.Dimension(105, 20));

        jButton2.setBackground(new java.awt.Color(76, 119, 102));
        jButton2.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(235, 230, 224));
        jButton2.setText("<");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(8, 17, 16));
        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(79, 41, 0));
        jLabel1.setText("DELETION PROCESS");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(220, 227, 238), null, null));

        jButton3.setBackground(new java.awt.Color(76, 119, 102));
        jButton3.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(235, 230, 224));
        jButton3.setText("DELETE");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel29.setBackground(new java.awt.Color(247, 247, 247));
        jLabel29.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(40, 40, 40));
        jLabel29.setText("BE GUIDED! IF AN ENTRY GETS DELETED BEFORE BEING CHECKED AND EXPORTED TO  A PDF FILE");
        jLabel29.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel29.setPreferredSize(new java.awt.Dimension(105, 20));

        jLabel30.setBackground(new java.awt.Color(247, 247, 247));
        jLabel30.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(40, 40, 40));
        jLabel30.setText("ALL RECORDS OF THIS ENTRY WILL BE ERASED! ");
        jLabel30.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel30.setPreferredSize(new java.awt.Dimension(105, 20));

        jLabel31.setBackground(new java.awt.Color(247, 247, 247));
        jLabel31.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(40, 40, 40));
        jLabel31.setText("PLEASE PROCEED WITH CAUTION!!");
        jLabel31.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel31.setPreferredSize(new java.awt.Dimension(105, 20));

        javax.swing.GroupLayout PANEL_3Layout = new javax.swing.GroupLayout(PANEL_3);
        PANEL_3.setLayout(PANEL_3Layout);
        PANEL_3Layout.setHorizontalGroup(
            PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_3Layout.createSequentialGroup()
                .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PANEL_3Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PANEL_3Layout.createSequentialGroup()
                        .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PANEL_3Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PANEL_3Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PANEL_3Layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PANEL_3Layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PANEL_3Layout.createSequentialGroup()
                                .addGap(249, 249, 249)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PANEL_3Layout.setVerticalGroup(
            PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PANEL_3, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(PANEL_3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        close();   
        proto_admin_UI main_L = new proto_admin_UI();
        main_L.setVisible(true);
        main_L.pack();
        main_L.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     deleteData();
    }//GEN-LAST:event_jButton3ActionPerformed

    
    private void deleteData() {
    String sUrl = "jdbc:mysql://localhost:3306/census_system_db";  // Ensure this is correct
    String sUser = "root";  // Your MySQL username
    String spass = "";  // Your MySQL password (if any)

    try (Connection Dbcon = DriverManager.getConnection(sUrl, sUser, spass)) {
        for (Map<String, String> data : dataList) {
            String email = data.get("Email");  // Extract email from the data map

            String deleteQuery = "DELETE FROM respondent_main_info WHERE a_respondent_email = ?";
            try (PreparedStatement stmt = Dbcon.prepareStatement(deleteQuery)) {
                stmt.setString(1, email);
                int rowsAffected = stmt.executeUpdate();
                if (rowsAffected > 0) {
                   //JOptionPane.showMessageDialog(this, "SUCCESSFULLY DELETED");
                    UpdateDB();
                    showTableDb();
                } else {
                    JOptionPane.showMessageDialog(this, "NO DATA TO DELETE");
                }
            }
        }
        JOptionPane.showMessageDialog(null, "Selected records deleted successfully.");
    } catch (SQLException e) {
        // Enhanced error handling to show the exact error message
        JOptionPane.showMessageDialog(null, "Error deleting records: " + e.getMessage());
        e.printStackTrace();  // This prints the detailed stack trace to the console for debugging
    }
}

    
    public void UpdateDB(){
        
        String sUrl = "jdbc:mysql://localhost:3306/census_system_db";
        String sUser = "root";
        String spass = "";
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Dbcon = DriverManager.getConnection(sUrl, sUser, spass);
            pst = Dbcon.prepareStatement("SELECT * FROM respondent_main_info ORDER BY a_time_forwarded DESC");
            
            result = pst.executeQuery();
            ResultSetMetaData resultData = result.getMetaData();
            
            int q = resultData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)admin_table.getModel();
            RecordTable.setRowCount(0);
            
            while(result.next()){
                Vector columnData = new Vector();
                
                for(int r = 1; r <= q; r++){
                    columnData.add(result.getString("a_respondent_email"));
                    columnData.add(result.getString("a_f_name"));
                    columnData.add(result.getString("a_l_name"));
                    columnData.add(result.getString("a_r_sex"));
                    columnData.add(result.getString("a_contact_no"));
                    columnData.add(result.getString("a_household_serial"));
                    columnData.add(result.getString("a_worker_validation"));
                    columnData.add(result.getString("a_worker_incharge"));
                    columnData.add(result.getString("a_time_forwarded"));
                    
                }
                RecordTable.addRow(columnData);
            }
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    public void showTableDb()throws SQLException{
        if(Dbcon == null || Dbcon.isClosed()){
            System.out.println("CHECK DATABASE CONNECTION");
            return;
        }
        String query = "SELECT * FROM respondent_main_info ORDER BY a_time_forwarded DESC";
        try(PreparedStatement stmt = Dbcon.prepareStatement(query)){
            
            ResultSet result = stmt.executeQuery();
            
            DefaultTableModel RecordTable = (DefaultTableModel)admin_table.getModel();
            RecordTable.setRowCount(0);
            
            
            
            while(result.next()){

                String r_email = result.getString("a_respondent_email");
                String first_name = result.getString("a_f_name");
                String last_name = result.getString("a_l_name");
                String sex = result.getString("a_r_sex");
                String contact = result.getString("a_contact_no");
                String household_s = result.getString("a_household_serial");
                String validation = result.getString("a_worker_validation");
                String worker = result.getString("a_worker_incharge");
                String forward_date = result.getString("a_time_forwarded");
                
                RecordTable.addRow(new Object[]{r_email, first_name,last_name, sex, contact, household_s, validation, worker, forward_date});
           }
        }catch (SQLException e){
            JOptionPane.showMessageDialog(this, "Error loading data" + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE );
        }     
    }
    
   
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FROM_ADMIN_DELETE_PROCESS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FROM_ADMIN_DELETE_PROCESS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FROM_ADMIN_DELETE_PROCESS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FROM_ADMIN_DELETE_PROCESS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Map<String, String> data = new HashMap<>();
                    data.put("FirstName", "");
                    data.put("LastName", "");
                    data.put("Address", "");
                    data.put("Email", "");
                    data.put("Contact", "");
                    data.put("Household", "");
                    data.put("Worker", "");
                    data.put("Suffix", "");
                    data.put("M_name", "");
                    data.put("Age", "");
                    data.put("B_date", "");
                    data.put("B_place", "");
                    data.put("Religion", "");
                    data.put("Citizenship", "");
                    data.put("Profession", "");
                    data.put("Enumer", "");
                    data.put("Build", "");
                    data.put("Housing", "");
                    data.put("Sex", "");
                    data.put("Status", "");
                    data.put("Attainment", "");
                    data.put("Date_Added", "");
                    data.put("Entry", "");

                    FROM_ADMIN_DELETE_PROCESS v_UI = new FROM_ADMIN_DELETE_PROCESS(dataList);
                new FROM_ADMIN_DELETE_PROCESS(dataList).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PANEL_3;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    // End of variables declaration//GEN-END:variables

    private static class JFrame extends Component {

        public JFrame() {
        }
    }
}
