/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sys_prototype_revised;

import java.awt.Component;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;



public class Main_login_PROTOTYPE extends javax.swing.JFrame {

    /**
     * Creates new form admin_login
     */
    public Main_login_PROTOTYPE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        username_login = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        password_login = new javax.swing.JPasswordField();
        sign_in_BT = new javax.swing.JButton();
        show_passwordBT = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sign_up = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 500));
        setUndecorated(true);
        setSize(new java.awt.Dimension(850, 500));

        jPanel2.setBackground(new java.awt.Color(220, 227, 238));
        jPanel2.setPreferredSize(new java.awt.Dimension(850, 500));

        jPanel3.setBackground(new java.awt.Color(247, 247, 247));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 350));

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(40, 40, 40));
        jLabel7.setText("username");
        jLabel7.setPreferredSize(new java.awt.Dimension(100, 20));

        username_login.setBackground(new java.awt.Color(247, 247, 247));
        username_login.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        username_login.setForeground(new java.awt.Color(40, 40, 40));
        username_login.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        username_login.setPreferredSize(new java.awt.Dimension(250, 35));

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(40, 40, 40));
        jLabel8.setText("password");
        jLabel8.setPreferredSize(new java.awt.Dimension(100, 20));

        password_login.setBackground(new java.awt.Color(247, 247, 247));
        password_login.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        password_login.setForeground(new java.awt.Color(40, 40, 40));
        password_login.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        password_login.setPreferredSize(new java.awt.Dimension(250, 35));

        sign_in_BT.setBackground(new java.awt.Color(247, 247, 247));
        sign_in_BT.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        sign_in_BT.setForeground(new java.awt.Color(40, 40, 40));
        sign_in_BT.setText("sign in");
        sign_in_BT.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sign_in_BT.setPreferredSize(new java.awt.Dimension(80, 20));
        sign_in_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_in_BTActionPerformed(evt);
            }
        });

        show_passwordBT.setBackground(new java.awt.Color(247, 247, 247));
        show_passwordBT.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        show_passwordBT.setForeground(new java.awt.Color(40, 40, 40));
        show_passwordBT.setText("show password");
        show_passwordBT.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        show_passwordBT.setPreferredSize(new java.awt.Dimension(112, 20));
        show_passwordBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_passwordBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(sign_in_BT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(username_login, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(password_login, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(show_passwordBT, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(username_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(password_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(show_passwordBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(sign_in_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jLabel4.setBackground(new java.awt.Color(36, 40, 51));
        jLabel4.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(40, 40, 40));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DATA COLLECTION SYSTEM");
        jLabel4.setPreferredSize(new java.awt.Dimension(400, 30));

        jLabel2.setBackground(new java.awt.Color(36, 40, 51));
        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(40, 40, 40));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FOR");
        jLabel2.setPreferredSize(new java.awt.Dimension(50, 30));

        jLabel3.setBackground(new java.awt.Color(36, 40, 51));
        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(40, 40, 40));
        jLabel3.setText("CENSUS");
        jLabel3.setMaximumSize(new java.awt.Dimension(90, 20));

        jLabel5.setBackground(new java.awt.Color(36, 40, 51));
        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(40, 40, 40));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("LOGIN HERE BUDDY");
        jLabel5.setPreferredSize(new java.awt.Dimension(130, 15));

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(40, 40, 40));
        jLabel6.setText("Don't have an account?");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel6.setPreferredSize(new java.awt.Dimension(130, 20));

        sign_up.setBackground(new java.awt.Color(247, 247, 247));
        sign_up.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        sign_up.setForeground(new java.awt.Color(40, 40, 40));
        sign_up.setText("sign up");
        sign_up.setActionCommand("signupbutton");
        sign_up.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sign_up.setPreferredSize(new java.awt.Dimension(75, 20));
        sign_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_upActionPerformed(evt);
            }
        });

        back_btn.setBackground(new java.awt.Color(76, 119, 102));
        back_btn.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        back_btn.setForeground(new java.awt.Color(235, 230, 224));
        back_btn.setText("x");
        back_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back_btn.setPreferredSize(new java.awt.Dimension(30, 30));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(sign_up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sign_up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sign_in_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_in_BTActionPerformed
        
        String password, username, query;
        String passw = null, usname = null;
        int founder = 0;
        String SUrl, SUser, Spass;
        SUrl = "jdbc:MySQL://localhost:3306/census_system_db";
        SUser = "root";
        Spass = "";
        
        username = username_login.getText();
        password = password_login.getText();
        
        Main_login_PROTOTYPE check = new Main_login_PROTOTYPE();
        String role = check.checker(username, password);
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, Spass);
            Statement stater = con.createStatement();
            
        if("".equals(username)){
            JOptionPane.showMessageDialog(new Jframe(),"Username is Required", "Error",  JOptionPane.ERROR_MESSAGE);   
        }else if("".equals(password)){
            JOptionPane.showMessageDialog(new Jframe(),"Password is Required", "Error",  JOptionPane.ERROR_MESSAGE);
        }else{
            if(null == role){
                int a = JOptionPane.showConfirmDialog(this, "Are you sure you have an account?", "DOUBLE CHECKING", JOptionPane.YES_NO_OPTION);
                    if(a == 1){
                        close();
                        PROTO_registerUI rUI = new PROTO_registerUI();
                        rUI.setVisible(true);
                        rUI.pack();
                        rUI.setLocationRelativeTo(null);
                        this.dispose();
                    }
            }else switch (role) {
                case "ADMIN" -> {
                    query = "SELECT * FROM login_details WHERE username = ? AND password = ?";
                    PreparedStatement pres = con.prepareStatement(query);
                    
                    pres.setString(1, username);
                    pres.setString(2, password);
                    
                    ResultSet result = pres.executeQuery();
                    while(result.next()){
                        passw = result.getString("confirm_password");
                        usname = result.getString("username");
                        founder = 1;
                    }
                    if(founder == 1 && password.equals(passw)){
                        String userDBN = "user_" + username;
                        String userDBURL = "jdbc:mysql://localhost:3306/" + userDBN;
                        Connection Dbcon = DriverManager.getConnection(userDBURL, SUser, Spass);
                        
                        //WORKER_DB_FOR_EDIT worker_UI = new WORKER_DB_FOR_EDIT(username, Dbcon);
                        
                        //WORKER_ADD a_worker = new WORKER_ADD(username, Dbcon);
                        
                        //forward_process_PROTO f_worker= new forward_process_PROTO(username, Dbcon);
                        //validation_process_PROTO v_worker= new validation_process_PROTO(username, Dbcon);
                        
                        close();
                        proto_admin_UI admin_UI = new proto_admin_UI();
                        admin_UI.setVisible(true);
                        admin_UI.pack();
                        admin_UI.setLocationRelativeTo(null);
                        this.dispose();
                    }
                } case "WORKER" -> {
                    
                    query = "SELECT * FROM login_details WHERE username = ? AND password = ?";
                    PreparedStatement pres = con.prepareStatement(query);
                    
                    pres.setString(1, username);
                    pres.setString(2, password);
                    
                    ResultSet result = pres.executeQuery();
                    while(result.next()){
                        passw = result.getString("confirm_password");
                        usname = result.getString("username");
                        founder = 1;
                    }
                    if(founder == 1 && password.equals(passw)){
                        String userDBN = "user_" + username;
                        String userDBURL = "jdbc:mysql://localhost:3306/" + userDBN;
                        Connection Dbcon = DriverManager.getConnection(userDBURL, SUser, Spass);
                        
                        WORKER_DB_FOR_EDIT worker_UI = new WORKER_DB_FOR_EDIT(username, Dbcon);
                        
                        WORKER_ADD a_worker = new WORKER_ADD(username, Dbcon);
                        
                        forward_process_PROTO f_worker= new forward_process_PROTO(username, Dbcon);
                        validation_process_PROTO v_worker= new validation_process_PROTO(username, Dbcon);
                        
                        close();
                        worker_UI.setVisible(true);
                        worker_UI.pack();
                        worker_UI.setLocationRelativeTo(null);
                        this.dispose();
                    }
                }
                default -> JOptionPane.showMessageDialog(new Jframe(),"Something ain't right", "Error",  JOptionPane.ERROR_MESSAGE);
            }
        }
        }catch(SQLException e){
            System.out.println("Error: " + e.getMessage());
            e.printStackTrace();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Main_login_PROTOTYPE.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_sign_in_BTActionPerformed

    private String checker(String username, String password){
        String role = null;
        String SUrl, SUser, Spass;
        SUrl = "jdbc:MySQL://localhost:3306/census_system_db";
        SUser = "root";
        Spass = "";
        
        String query = "SELECT role FROM login_details WHERE username = ? AND password = ?";
        try(Connection con = DriverManager.getConnection(SUrl,SUser,Spass);
            PreparedStatement stmt = con.prepareStatement(query)){
            stmt.setString(1, username);
            stmt.setString(2, password);
            
            ResultSet result = stmt.executeQuery();

            if(result.next()) {
                role = result.getString("role");
               
            }
        }catch(SQLException r){
            JOptionPane.showMessageDialog(this, "Database error", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return role;
    }
    
    /*private boolean LoginAdmin(Connection con, String username, String role) throws SQLException{
        String query = "SELECT username,role FROM census_login_table WHERE username = ?";
        try(PreparedStatement stmt = con.prepareStatement(query)){
            stmt.setString(1, username);
            
            ResultSet result = stmt.executeQuery();
            
            return result.next();
        }
    }
    
    private boolean LoginWorker(Connection con, String username, String role) throws SQLException{
        String query = "SELECT username,role FROM census_login_table WHERE username = ?";
        try(PreparedStatement stmt = con.prepareStatement(query)){
            stmt.setString(1, username);
            
            ResultSet result = stmt.executeQuery();
            
            return result.next();
        }
    }*/
    
    private void sign_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_upActionPerformed
        close();
        PROTO_registerUI rUI = new PROTO_registerUI();
        rUI.setVisible(true);
        rUI.pack();
        rUI.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_sign_upActionPerformed

    private void show_passwordBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_passwordBTActionPerformed
        if(show_passwordBT.isSelected()){
            password_login.setEchoChar((char) 0);
        }else{
            password_login.setEchoChar('*');
        }
    }//GEN-LAST:event_show_passwordBTActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed

        int a = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit", "EXIT", JOptionPane.YES_NO_OPTION);
        if(a == 0){
            System.exit(0);
        }

    }//GEN-LAST:event_back_btnActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_login_PROTOTYPE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_login_PROTOTYPE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_login_PROTOTYPE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_login_PROTOTYPE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
        }catch(ClassNotFoundException r){
            return;
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_login_PROTOTYPE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField password_login;
    private javax.swing.JCheckBox show_passwordBT;
    private javax.swing.JButton sign_in_BT;
    private javax.swing.JButton sign_up;
    public static javax.swing.JTextField username_login;
    // End of variables declaration//GEN-END:variables
    
    private static class Jframe extends Component{
        public Jframe(){
        }
    }

}
