/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sys_prototype_revised;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.Component;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.*;


/**
 *
 * @author Rodulfo R. Lopez
 */
public class PROTO_registerUI extends javax.swing.JFrame {

    /**
     * Creates new form registerUI
     */
    public PROTO_registerUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_main = new javax.swing.JPanel();
        panel_display = new javax.swing.JPanel();
        address_registration = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        role_registration = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        name_registration = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        bday_registration = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        age_registration = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        contact_registration = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        email_registration = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cluster_registration = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        password_registration = new javax.swing.JPasswordField();
        password_confirm_registration = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        username_registration = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        code_registration = new javax.swing.JTextField();
        attainment_combobox_registration = new javax.swing.JComboBox<>();
        sex_registration = new javax.swing.JComboBox<>();
        status_registration = new javax.swing.JComboBox<>();
        show_passwordBT = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        return_main = new javax.swing.JButton();
        register_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 900, 500));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(850, 470));
        setSize(new java.awt.Dimension(850, 500));

        panel_main.setBackground(new java.awt.Color(223, 227, 238));
        panel_main.setForeground(new java.awt.Color(247, 247, 247));
        panel_main.setPreferredSize(new java.awt.Dimension(850, 470));

        panel_display.setBackground(new java.awt.Color(247, 247, 247));
        panel_display.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_display.setPreferredSize(new java.awt.Dimension(800, 380));

        address_registration.setBackground(new java.awt.Color(247, 247, 247));
        address_registration.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        address_registration.setForeground(new java.awt.Color(40, 40, 40));
        address_registration.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        address_registration.setPreferredSize(new java.awt.Dimension(300, 25));
        address_registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_registrationActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(40, 40, 40));
        jLabel4.setText("cluster");
        jLabel4.setPreferredSize(new java.awt.Dimension(70, 20));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(40, 40, 40));
        jLabel5.setText("sign up as");
        jLabel5.setPreferredSize(new java.awt.Dimension(80, 20));

        role_registration.setBackground(new java.awt.Color(247, 247, 247));
        role_registration.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        role_registration.setForeground(new java.awt.Color(40, 40, 40));
        role_registration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "WORKER" }));
        role_registration.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        role_registration.setPreferredSize(new java.awt.Dimension(105, 25));
        role_registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                role_registrationActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(40, 40, 40));
        jLabel6.setText("birth date");
        jLabel6.setPreferredSize(new java.awt.Dimension(60, 20));

        name_registration.setBackground(new java.awt.Color(247, 247, 247));
        name_registration.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        name_registration.setForeground(new java.awt.Color(40, 40, 40));
        name_registration.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        name_registration.setPreferredSize(new java.awt.Dimension(200, 25));
        name_registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_registrationActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(40, 40, 40));
        jLabel7.setText("name");
        jLabel7.setPreferredSize(new java.awt.Dimension(40, 20));

        bday_registration.setBackground(new java.awt.Color(247, 247, 247));
        bday_registration.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        bday_registration.setForeground(new java.awt.Color(40, 40, 40));
        bday_registration.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bday_registration.setPreferredSize(new java.awt.Dimension(140, 25));
        bday_registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bday_registrationActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(40, 40, 40));
        jLabel8.setText("sex");
        jLabel8.setPreferredSize(new java.awt.Dimension(30, 20));

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(40, 40, 40));
        jLabel9.setText("age");
        jLabel9.setPreferredSize(new java.awt.Dimension(30, 20));

        age_registration.setBackground(new java.awt.Color(247, 247, 247));
        age_registration.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        age_registration.setForeground(new java.awt.Color(40, 40, 40));
        age_registration.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        age_registration.setPreferredSize(new java.awt.Dimension(50, 25));
        age_registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                age_registrationActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(40, 40, 40));
        jLabel10.setText("contact no.");
        jLabel10.setPreferredSize(new java.awt.Dimension(70, 20));

        contact_registration.setBackground(new java.awt.Color(247, 247, 247));
        contact_registration.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        contact_registration.setForeground(new java.awt.Color(40, 40, 40));
        contact_registration.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        contact_registration.setPreferredSize(new java.awt.Dimension(130, 25));
        contact_registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact_registrationActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(40, 40, 40));
        jLabel11.setText("email");
        jLabel11.setPreferredSize(new java.awt.Dimension(40, 20));

        email_registration.setBackground(new java.awt.Color(247, 247, 247));
        email_registration.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        email_registration.setForeground(new java.awt.Color(40, 40, 40));
        email_registration.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        email_registration.setPreferredSize(new java.awt.Dimension(200, 25));
        email_registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_registrationActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(40, 40, 40));
        jLabel12.setText("address");
        jLabel12.setPreferredSize(new java.awt.Dimension(70, 20));

        cluster_registration.setBackground(new java.awt.Color(247, 247, 247));
        cluster_registration.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        cluster_registration.setForeground(new java.awt.Color(40, 40, 40));
        cluster_registration.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cluster_registration.setPreferredSize(new java.awt.Dimension(70, 25));
        cluster_registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cluster_registrationActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(40, 40, 40));
        jLabel13.setText("status");
        jLabel13.setPreferredSize(new java.awt.Dimension(70, 20));

        jLabel14.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(40, 40, 40));
        jLabel14.setText("attainment");
        jLabel14.setPreferredSize(new java.awt.Dimension(100, 20));

        jLabel15.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(40, 40, 40));
        jLabel15.setText("password");
        jLabel15.setPreferredSize(new java.awt.Dimension(70, 20));

        password_registration.setBackground(new java.awt.Color(247, 247, 247));
        password_registration.setForeground(new java.awt.Color(40, 40, 40));
        password_registration.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        password_registration.setPreferredSize(new java.awt.Dimension(145, 25));
        password_registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_registrationActionPerformed(evt);
            }
        });

        password_confirm_registration.setBackground(new java.awt.Color(247, 247, 247));
        password_confirm_registration.setForeground(new java.awt.Color(40, 40, 40));
        password_confirm_registration.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        password_confirm_registration.setPreferredSize(new java.awt.Dimension(145, 25));
        password_confirm_registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_confirm_registrationActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(40, 40, 40));
        jLabel16.setText("confirm password");
        jLabel16.setPreferredSize(new java.awt.Dimension(120, 20));

        jLabel18.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(40, 40, 40));
        jLabel18.setText("preferred username");
        jLabel18.setPreferredSize(new java.awt.Dimension(120, 20));

        username_registration.setBackground(new java.awt.Color(247, 247, 247));
        username_registration.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        username_registration.setForeground(new java.awt.Color(40, 40, 40));
        username_registration.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        username_registration.setPreferredSize(new java.awt.Dimension(200, 25));
        username_registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_registrationActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Bahnschrift", 0, 10)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 2, 0));
        jLabel19.setText("* note that username and validation code are entirely up to you, please be responsible and remember it all the time");
        jLabel19.setPreferredSize(new java.awt.Dimension(515, 20));

        jLabel20.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(40, 40, 40));
        jLabel20.setText("personalized validation code");
        jLabel20.setPreferredSize(new java.awt.Dimension(170, 20));

        code_registration.setBackground(new java.awt.Color(247, 247, 247));
        code_registration.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        code_registration.setForeground(new java.awt.Color(40, 40, 40));
        code_registration.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        code_registration.setPreferredSize(new java.awt.Dimension(200, 25));
        code_registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                code_registrationActionPerformed(evt);
            }
        });

        attainment_combobox_registration.setBackground(new java.awt.Color(247, 247, 247));
        attainment_combobox_registration.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        attainment_combobox_registration.setForeground(new java.awt.Color(40, 40, 40));
        attainment_combobox_registration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elementary", "High School", "College", "Post Grad", "Vocational" }));
        attainment_combobox_registration.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        attainment_combobox_registration.setPreferredSize(new java.awt.Dimension(125, 25));
        attainment_combobox_registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attainment_combobox_registrationActionPerformed(evt);
            }
        });

        sex_registration.setBackground(new java.awt.Color(247, 247, 247));
        sex_registration.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        sex_registration.setForeground(new java.awt.Color(40, 40, 40));
        sex_registration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        sex_registration.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sex_registration.setPreferredSize(new java.awt.Dimension(85, 25));
        sex_registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sex_registrationActionPerformed(evt);
            }
        });

        status_registration.setBackground(new java.awt.Color(247, 247, 247));
        status_registration.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        status_registration.setForeground(new java.awt.Color(40, 40, 40));
        status_registration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married", "Widowed" }));
        status_registration.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        status_registration.setPreferredSize(new java.awt.Dimension(100, 25));
        status_registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                status_registrationActionPerformed(evt);
            }
        });

        show_passwordBT.setBackground(new java.awt.Color(247, 247, 247));
        show_passwordBT.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        show_passwordBT.setForeground(new java.awt.Color(40, 40, 40));
        show_passwordBT.setText("show password");
        show_passwordBT.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        show_passwordBT.setPreferredSize(new java.awt.Dimension(112, 20));
        show_passwordBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_passwordBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_displayLayout = new javax.swing.GroupLayout(panel_display);
        panel_display.setLayout(panel_displayLayout);
        panel_displayLayout.setHorizontalGroup(
            panel_displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_displayLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panel_displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_displayLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_displayLayout.createSequentialGroup()
                        .addGroup(panel_displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_displayLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_displayLayout.createSequentialGroup()
                                .addComponent(bday_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(age_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_displayLayout.createSequentialGroup()
                                .addGroup(panel_displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sex_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel_displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contact_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(email_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(username_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                        .addGroup(panel_displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(address_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_displayLayout.createSequentialGroup()
                                .addGroup(panel_displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cluster_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panel_displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_displayLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(status_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel_displayLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel_displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(attainment_combobox_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panel_displayLayout.createSequentialGroup()
                                .addGroup(panel_displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(password_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panel_displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_displayLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(panel_displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(password_confirm_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(panel_displayLayout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(show_passwordBT, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panel_displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panel_displayLayout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(role_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(code_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))))
        );
        panel_displayLayout.setVerticalGroup(
            panel_displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_displayLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panel_displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(panel_displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(panel_displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_displayLayout.createSequentialGroup()
                        .addGroup(panel_displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(panel_displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bday_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(age_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cluster_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(attainment_combobox_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(status_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(panel_displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(panel_displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contact_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password_confirm_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sex_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(panel_displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(show_passwordBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(panel_displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addGroup(panel_displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(code_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(panel_displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(role_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel17.setBackground(new java.awt.Color(36, 40, 51));
        jLabel17.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(40, 40, 40));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("REGISTRATION");
        jLabel17.setPreferredSize(new java.awt.Dimension(130, 25));

        return_main.setBackground(new java.awt.Color(76, 119, 102));
        return_main.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        return_main.setForeground(new java.awt.Color(235, 230, 224));
        return_main.setText("<");
        return_main.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        return_main.setPreferredSize(new java.awt.Dimension(30, 30));
        return_main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_mainActionPerformed(evt);
            }
        });

        register_button.setBackground(new java.awt.Color(255, 255, 240));
        register_button.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        register_button.setForeground(new java.awt.Color(40, 40, 40));
        register_button.setText("register");
        register_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        register_button.setPreferredSize(new java.awt.Dimension(50, 20));
        register_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_mainLayout = new javax.swing.GroupLayout(panel_main);
        panel_main.setLayout(panel_mainLayout);
        panel_mainLayout.setHorizontalGroup(
            panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_mainLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(register_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panel_display, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panel_mainLayout.createSequentialGroup()
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(return_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25))
        );
        panel_mainLayout.setVerticalGroup(
            panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_mainLayout.createSequentialGroup()
                .addGroup(panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_mainLayout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(return_main, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_mainLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_display, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(register_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        register_button.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void password_confirm_registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_confirm_registrationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_confirm_registrationActionPerformed

    private void password_registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_registrationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_registrationActionPerformed

    private void email_registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_registrationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_registrationActionPerformed

    private void contact_registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact_registrationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contact_registrationActionPerformed

    private void age_registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_age_registrationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_age_registrationActionPerformed

    private void bday_registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bday_registrationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bday_registrationActionPerformed

    private void name_registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_registrationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_registrationActionPerformed

    private void register_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_buttonActionPerformed
        String v_code, name, birth_date, age, sex, contact_no, email, username, address, cluster, status, attainment, password, confirm_password, role;
        String SUrl = "jdbc:mysql://localhost:3306/census_system_db";
        String SUser = "root";
        String Spass = "";

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, Spass);

            // Validate inputs
            if (isInputValid()) {
                v_code = code_registration.getText();
                name = name_registration.getText(); 
                birth_date = bday_registration.getText();
                age = age_registration.getText(); 
                sex = sex_registration.getSelectedItem().toString();
                contact_no = contact_registration.getText();
                email = email_registration.getText();
                username = username_registration.getText();
                address = address_registration.getText();
                cluster = cluster_registration.getText();
                status = status_registration.getSelectedItem().toString();
                attainment = attainment_combobox_registration.getSelectedItem().toString();
                password = password_registration.getText();
                confirm_password = password_confirm_registration.getText();
                role = role_registration.getSelectedItem().toString();

                if (password.equals(confirm_password)) {
                    // Check if the user is trying to register as an admin
                    if (role.equals("ADMIN") && adminExists(con)) {
                        showError("Admin Already exists! Register as a Worker or contact the Admin for help.");
                    } else {
                        // Proceed with registration
                        registerUser(con, v_code, name, email, username, password, confirm_password, role,
                                     birth_date, age, sex, contact_no,
                                     address, cluster, status, attainment);
                        
                        String createDBQ = "CREATE DATABASE IF NOT EXISTS user_" + username;
                        Statement queryDB = con.createStatement();
                        queryDB.executeUpdate(createDBQ);

                        String createDB_T = "CREATE TABLE IF NOT EXISTS user_" + username + ".res_info" + 
                        "(respondent_email VARCHAR(120) PRIMARY KEY," +
                        "f_name VARCHAR(120) NOT NULL,"+
                        "l_name VARCHAR(120) NOT NULL," +
                        "address VARCHAR(120) NOT NULL," +
                        "contact_no VARCHAR(120) NOT NULL," +
                        "household_serial VARCHAR(120) NOT NULL," +
                        "date_listed DATE," +
                        "worker_incharge VARCHAR(120) NOT NULL," +
                        "suffix VARCHAR(120) NOT NULL," +
                        "m_name VARCHAR(120) NOT NULL," +
                        "r_sex VARCHAR(120) NOT NULL," +
                        "r_status VARCHAR(120) NOT NULL," +
                        "r_age VARCHAR(120) NOT NULL," +
                        "r_birthdate VARCHAR(120) NOT NULL," +
                        "r_birthplace VARCHAR(120) NOT NULL," +
                        "r_religion VARCHAR(120) NOT NULL," +
                        "r_citizenship VARCHAR(120) NOT NULL," +
                        "r_profession VARCHAR(120) NOT NULL," +
                        "r_attainment VARCHAR(120) NOT NULL," +
                        "enumeration_serial VARCHAR(120) NOT NULL," +
                        "building_serial VARCHAR(120) NOT NULL," +
                        "housing_unit_serial VARCHAR(120) NOT NULL," +
                        "validation  VARCHAR(255) DEFAULT 'NOT YET VALIDATED'," +
                        "time_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP)";

                        queryDB.executeUpdate(createDB_T);
                        
                        clearFields();
                        JOptionPane.showMessageDialog(this, "You are Registered Successfully");
                        
                        String UserDbUrl = "jdbc:mysql://localhost:3306/user_" + username;
                        Connection Dbcon = DriverManager.getConnection(UserDbUrl, SUser, Spass);
                        
                        WORKER_DB_FOR_EDIT worker = new WORKER_DB_FOR_EDIT(username, Dbcon);
                        
                        close();
                        Main_login_PROTOTYPE admin_L = new Main_login_PROTOTYPE();
                        admin_L.setVisible(true);
                        admin_L.pack();
                        admin_L.setLocationRelativeTo(null);
                        this.dispose();

                    }
                } else {
                    showError("Passwords do not match. Please double-check.");
                }
            }
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }

    private boolean isInputValid() {
        if ("".equals(name_registration.getText())) {
            showError("Name is Required");
            return false;
        } else if ("".equals(bday_registration.getText())) {
            showError("Your birthday is Required");
            return false;
        } else if ("".equals(age_registration.getText())) {
            showError("Your age is Required");
            return false;
        } else if ("".equals(contact_registration.getText())) {
            showError("Your contact number is Required");
            return false;
        } else if ("".equals(email_registration.getText())) {
            showError("Your email is Required");
            return false;
        } else if ("".equals(username_registration.getText())) {
            showError("Your preferred username is very important");
            return false;
        } else if ("".equals(address_registration.getText())) {
            showError("Your address is Required");
            return false;
        } else if ("".equals(cluster_registration.getText())) {
            showError("The cluster you are from is Required");
            return false;
        } else if ("".equals(password_registration.getText())) {
            showError("Your password is Required");
            return false;
        } else if ("".equals(password_confirm_registration.getText())) {
            showError("You must confirm your password");
            return false;
        } else if ("".equals(code_registration.getText())) {
            showError("Your personalized code is important");
            return false;
        }
        return true;
    }

    private boolean adminExists(Connection con) throws SQLException {
        String checkAdminQuery = "SELECT COUNT(*) FROM login_details WHERE role = 'ADMIN'";
            try (PreparedStatement checkAdminSTMT = con.prepareStatement(checkAdminQuery)) {
                ResultSet result = checkAdminSTMT.executeQuery();
                result.next();
                return result.getInt(1) > 0; // Returns true if at least one ADMIN exists
            }

    }

    private void registerUser(Connection con, String v_code, String name, String email,
                              String username, String password, String confirm_password, String role,
                              String birth_date, String age,
                              String sex, String contact_no,
                              String address, String cluster,
                              String status, String attainment) throws SQLException {

        String query = "INSERT INTO login_details(username, password, confirm_password, role, validation_code, name, email," + 
                            "birth_date, age, sex, contact_no, address," +
                            "cluster, user_status, attainment) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        
        try (PreparedStatement insertLoginStmt = con.prepareStatement(query)) {
            insertLoginStmt.setString(1, username);
            insertLoginStmt.setString(2, password);
            insertLoginStmt.setString(3, confirm_password);
            insertLoginStmt.setString(4, role);
            insertLoginStmt.setString(5, v_code);
            insertLoginStmt.setString(6, name);
            insertLoginStmt.setString(7, email);
            insertLoginStmt.setString(8, birth_date);
            insertLoginStmt.setString(9, age);
            insertLoginStmt.setString(10,sex);
            insertLoginStmt.setString(11, contact_no);
            insertLoginStmt.setString(12, address);
            insertLoginStmt.setString(13, cluster);
            insertLoginStmt.setString(14, status);
            insertLoginStmt.setString(15, attainment);
            insertLoginStmt.executeUpdate();
        }
                
    }

    private void clearFields() {
        code_registration.setText("");
        name_registration.setText("");
        bday_registration.setText("");
        age_registration.setText("");
        contact_registration.setText("");
        email_registration.setText("");
        username_registration.setText("");
        address_registration.setText("");
        cluster_registration.setText("");
        password_registration.setText("");
        password_confirm_registration.setText("");
    }

    private void showError(String message) {
         JOptionPane.showMessageDialog(new JFrame(), message,"Error", JOptionPane.ERROR_MESSAGE);

    }//GEN-LAST:event_register_buttonActionPerformed

    private void role_registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_role_registrationActionPerformed
        
    }//GEN-LAST:event_role_registrationActionPerformed

    private void username_registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_registrationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_registrationActionPerformed

    private void code_registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_code_registrationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_code_registrationActionPerformed

    private void return_mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return_mainActionPerformed
        close();
        Main_login_PROTOTYPE main_L = new Main_login_PROTOTYPE();
        main_L.setVisible(true);
        main_L.pack();
        main_L.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_return_mainActionPerformed

    private void sex_registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sex_registrationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sex_registrationActionPerformed

    private void show_passwordBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_passwordBTActionPerformed
        if(show_passwordBT.isSelected()){
            password_registration.setEchoChar((char) 0);
            password_confirm_registration.setEchoChar((char) 0);
        }else{
            password_registration.setEchoChar('*');
            password_confirm_registration.setEchoChar('*');
        }
    }//GEN-LAST:event_show_passwordBTActionPerformed

    private void address_registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_registrationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_registrationActionPerformed

    private void attainment_combobox_registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attainment_combobox_registrationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attainment_combobox_registrationActionPerformed

    private void cluster_registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cluster_registrationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cluster_registrationActionPerformed

    private void status_registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_status_registrationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_status_registrationActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WORKER_DB_FOR_EDIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WORKER_DB_FOR_EDIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WORKER_DB_FOR_EDIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WORKER_DB_FOR_EDIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PROTO_registerUI().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address_registration;
    private javax.swing.JTextField age_registration;
    private javax.swing.JComboBox<String> attainment_combobox_registration;
    private javax.swing.JTextField bday_registration;
    private javax.swing.JTextField cluster_registration;
    private javax.swing.JTextField code_registration;
    private javax.swing.JTextField contact_registration;
    private javax.swing.JTextField email_registration;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField name_registration;
    private javax.swing.JPanel panel_display;
    private javax.swing.JPanel panel_main;
    private javax.swing.JPasswordField password_confirm_registration;
    private javax.swing.JPasswordField password_registration;
    private javax.swing.JButton register_button;
    private javax.swing.JButton return_main;
    private javax.swing.JComboBox<String> role_registration;
    private javax.swing.JComboBox<String> sex_registration;
    private javax.swing.JCheckBox show_passwordBT;
    private javax.swing.JComboBox<String> status_registration;
    private javax.swing.JTextField username_registration;
    // End of variables declaration//GEN-END:variables

    private static class JFrame extends Component {

        public JFrame() {
        }
    }
}
