/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sys_prototype_revised;

import java.awt.Component;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.*;
import java.util.HashMap;
import java.util.Map;
import javax.swing.SwingUtilities;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;



public class SHOW_WHO_WORKER extends javax.swing.JFrame {

    private static String username;
    private static Connection Dbcon;

    private String sUrl = "jdbc:mysql://localhost:3306/census_system_db";
    private String sUser = "root";
    private String spass = "";
        
        
    private static PreparedStatement pst;
    private static ResultSet result;
    
    
    public SHOW_WHO_WORKER(String username, Connection Dbcon) {
        this.username = username;
        this.Dbcon = Dbcon;
        initComponents();
        SwingUtilities.invokeLater(this::connectLoadData);
        


        
    }
    
    public void connectLoadData(){
        try{
            connectToDB();
            UpdateDB();
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE );
        }
    }
    
    public void connectToDB() throws SQLException{
        String SUrl = "jdbc:mysql://localhost:3306/census_system_db";
        String SUser = "root";
        String Spass = "";
        Dbcon = DriverManager.getConnection(SUrl, SUser, Spass);
    }
    
    private void showError(String message) {
         JOptionPane.showMessageDialog(new SHOW_WHO_WORKER.JFrame(), message,"Error", JOptionPane.ERROR_MESSAGE);

    }

    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PANEL_3 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        w_full_name = new javax.swing.JLabel();
        w_user = new javax.swing.JLabel();
        w_email = new javax.swing.JLabel();
        w_sex = new javax.swing.JLabel();
        w_age = new javax.swing.JLabel();
        w_status = new javax.swing.JLabel();
        w_birthdate = new javax.swing.JLabel();
        w_cluster = new javax.swing.JLabel();
        w_attainment = new javax.swing.JLabel();
        w_contact = new javax.swing.JLabel();
        w_address = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        PANEL_3.setBackground(new java.awt.Color(220, 227, 238));
        PANEL_3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PANEL_3.setForeground(new java.awt.Color(247, 247, 247));
        PANEL_3.setPreferredSize(new java.awt.Dimension(850, 500));

        jLabel28.setBackground(new java.awt.Color(247, 247, 247));
        jLabel28.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(40, 40, 40));
        jLabel28.setText("PERSONAL INFORMATION");
        jLabel28.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel28.setPreferredSize(new java.awt.Dimension(105, 20));

        jLabel29.setBackground(new java.awt.Color(0, 0, 0));
        jLabel29.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(26, 72, 98));
        jLabel29.setText("Full Name");

        jLabel31.setBackground(new java.awt.Color(247, 247, 247));
        jLabel31.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(26, 72, 98));
        jLabel31.setText("Username");

        jLabel32.setBackground(new java.awt.Color(247, 247, 247));
        jLabel32.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(26, 72, 98));
        jLabel32.setText("Email");

        jLabel33.setBackground(new java.awt.Color(247, 247, 247));
        jLabel33.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(26, 72, 98));
        jLabel33.setText("Sex");

        jLabel34.setBackground(new java.awt.Color(247, 247, 247));
        jLabel34.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(26, 72, 98));
        jLabel34.setText("Age");

        jLabel35.setBackground(new java.awt.Color(247, 247, 247));
        jLabel35.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(26, 72, 98));
        jLabel35.setText("Status");

        jLabel36.setBackground(new java.awt.Color(247, 247, 247));
        jLabel36.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(26, 72, 98));
        jLabel36.setText("Birthdate (mm/dd/yyyy) ");

        jLabel37.setBackground(new java.awt.Color(247, 247, 247));
        jLabel37.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(26, 72, 98));
        jLabel37.setText("From Cluster");

        jLabel39.setBackground(new java.awt.Color(247, 247, 247));
        jLabel39.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(26, 72, 98));
        jLabel39.setText("Attainment");

        jLabel42.setBackground(new java.awt.Color(247, 247, 247));
        jLabel42.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(26, 72, 98));
        jLabel42.setText("Address");

        jLabel43.setBackground(new java.awt.Color(247, 247, 247));
        jLabel43.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(26, 72, 98));
        jLabel43.setText("Contact No.");

        jButton2.setBackground(new java.awt.Color(76, 119, 102));
        jButton2.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(235, 230, 224));
        jButton2.setText("<");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(8, 17, 16));
        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(79, 41, 0));
        jLabel1.setText("WORKER DETAILS");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(220, 227, 238), null, null));

        w_full_name.setBackground(new java.awt.Color(220, 227, 238));
        w_full_name.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        w_full_name.setForeground(new java.awt.Color(40, 40, 40));
        w_full_name.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        w_full_name.setPreferredSize(new java.awt.Dimension(105, 20));

        w_user.setBackground(new java.awt.Color(247, 247, 247));
        w_user.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        w_user.setForeground(new java.awt.Color(40, 40, 40));
        w_user.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        w_user.setPreferredSize(new java.awt.Dimension(105, 20));

        w_email.setBackground(new java.awt.Color(247, 247, 247));
        w_email.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        w_email.setForeground(new java.awt.Color(40, 40, 40));
        w_email.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        w_email.setPreferredSize(new java.awt.Dimension(105, 20));

        w_sex.setBackground(new java.awt.Color(247, 247, 247));
        w_sex.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        w_sex.setForeground(new java.awt.Color(40, 40, 40));
        w_sex.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        w_sex.setPreferredSize(new java.awt.Dimension(105, 20));

        w_age.setBackground(new java.awt.Color(247, 247, 247));
        w_age.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        w_age.setForeground(new java.awt.Color(40, 40, 40));
        w_age.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        w_age.setPreferredSize(new java.awt.Dimension(105, 20));

        w_status.setBackground(new java.awt.Color(247, 247, 247));
        w_status.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        w_status.setForeground(new java.awt.Color(40, 40, 40));
        w_status.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        w_status.setPreferredSize(new java.awt.Dimension(105, 20));

        w_birthdate.setBackground(new java.awt.Color(220, 227, 238));
        w_birthdate.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        w_birthdate.setForeground(new java.awt.Color(40, 40, 40));
        w_birthdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        w_birthdate.setPreferredSize(new java.awt.Dimension(105, 20));

        w_cluster.setBackground(new java.awt.Color(220, 227, 238));
        w_cluster.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        w_cluster.setForeground(new java.awt.Color(40, 40, 40));
        w_cluster.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        w_cluster.setPreferredSize(new java.awt.Dimension(105, 20));

        w_attainment.setBackground(new java.awt.Color(220, 227, 238));
        w_attainment.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        w_attainment.setForeground(new java.awt.Color(40, 40, 40));
        w_attainment.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        w_attainment.setPreferredSize(new java.awt.Dimension(105, 20));

        w_contact.setBackground(new java.awt.Color(220, 227, 238));
        w_contact.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        w_contact.setForeground(new java.awt.Color(40, 40, 40));
        w_contact.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        w_contact.setPreferredSize(new java.awt.Dimension(105, 20));

        w_address.setBackground(new java.awt.Color(220, 227, 238));
        w_address.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        w_address.setForeground(new java.awt.Color(40, 40, 40));
        w_address.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        w_address.setPreferredSize(new java.awt.Dimension(105, 20));

        javax.swing.GroupLayout PANEL_3Layout = new javax.swing.GroupLayout(PANEL_3);
        PANEL_3.setLayout(PANEL_3Layout);
        PANEL_3Layout.setHorizontalGroup(
            PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_3Layout.createSequentialGroup()
                .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PANEL_3Layout.createSequentialGroup()
                        .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PANEL_3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PANEL_3Layout.createSequentialGroup()
                                        .addGap(170, 170, 170)
                                        .addComponent(w_user, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PANEL_3Layout.createSequentialGroup()
                                        .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(w_full_name, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel29)
                                            .addComponent(jLabel36)
                                            .addComponent(w_birthdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20, 20, 20)
                                        .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(w_address, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel42)
                                                .addGroup(PANEL_3Layout.createSequentialGroup()
                                                    .addGap(143, 143, 143)
                                                    .addComponent(jLabel32))
                                                .addComponent(w_email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel31))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(w_age, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(w_sex, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel34)
                                            .addComponent(jLabel33)))
                                    .addGroup(PANEL_3Layout.createSequentialGroup()
                                        .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PANEL_3Layout.createSequentialGroup()
                                                .addComponent(w_cluster, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(w_attainment, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PANEL_3Layout.createSequentialGroup()
                                                .addComponent(jLabel37)
                                                .addGap(95, 95, 95)
                                                .addComponent(jLabel39)))
                                        .addGap(18, 18, 18)
                                        .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(w_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel43))
                                        .addGap(18, 18, 18)
                                        .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel35)
                                            .addComponent(w_status, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(PANEL_3Layout.createSequentialGroup()
                                .addGap(211, 211, 211)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 17, Short.MAX_VALUE))
                    .addGroup(PANEL_3Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PANEL_3Layout.setVerticalGroup(
            PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel31)
                        .addComponent(jLabel32)
                        .addComponent(jLabel34)))
                .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(w_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(w_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(w_full_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(w_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PANEL_3Layout.createSequentialGroup()
                        .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36)
                            .addComponent(jLabel42))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(w_birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(w_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PANEL_3Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(w_sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PANEL_3Layout.createSequentialGroup()
                        .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANEL_3Layout.createSequentialGroup()
                                .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel39)
                                    .addComponent(jLabel43)
                                    .addComponent(jLabel35))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(w_attainment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(w_cluster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(w_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(w_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PANEL_3, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(PANEL_3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        close();
        WORKER_DB_FOR_EDIT main_L = new WORKER_DB_FOR_EDIT(username, Dbcon);
        main_L.setVisible(true);
        main_L.pack();
        main_L.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
  
    public void UpdateDB(){
        
        String sUrl = "jdbc:mysql://localhost:3306/census_system_db";
        String sUser = "root";
        String spass = "";
        
        String query = "SELECT * FROM login_details WHERE username = '"+username+"'";
        try(Connection Dbcon = DriverManager.getConnection(sUrl, sUser, spass);
            Statement stmt = Dbcon.createStatement();
            ResultSet result = stmt.executeQuery(query)){
            
            if(result.next()){
                String full_n = result.getString("name");
                String user_n = result.getString("username");
                String email = result.getString("email");
                String age = result.getString("age");
                String bday = result.getString("birth_date");
                String address = result.getString("address");
                String sex = result.getString("sex");
                String cluster = result.getString("cluster");
                String attainment = result.getString("attainment");
                String contact = result.getString("contact_no");
                String status = result.getString("user_status");
                
                w_full_name.setText(full_n);
                w_user.setText(user_n);
                w_email.setText(email);
                w_age.setText(age);
                w_birthdate.setText(bday);
                w_address.setText(address);
                w_sex.setText(sex);
                w_cluster.setText(cluster);
                w_attainment.setText(attainment);
                w_contact.setText(contact);
                w_status.setText(status);

                
            }
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    /*public void showTableDb()throws SQLException{
        if(Dbcon == null || Dbcon.isClosed()){
            System.out.println("CHECK DATABASE CONNECTION");
            return;
        }
        String query = "SELECT * FROM res_info ORDER BY time_created DESC";
        try(PreparedStatement stmt = Dbcon.prepareStatement(query)){
            
            ResultSet result = stmt.executeQuery();
            
            DefaultTableModel RecordTable = (DefaultTableModel)record_table.getModel();
            RecordTable.setRowCount(0);
            
            
            
            while(result.next()){
                /*StringBuilder details = new StringBuilder();
                ResultSetMetaData metadata = result.getMetaData();
                int columnCount = metadata.getColumnCount();
                
                String r_email = result.getString("respondent_email");
                String first_name = result.getString("f_name");
                String last_name = result.getString("l_name");
                String r_add = result.getString("address");
                String contact = result.getString("contact_no");
                String household_s = result.getString("household_serial");
                String lisiting_date = result.getString("date_listed");
                String w_valid = result.getString("validation");
                
                RecordTable.addRow(new Object[]{r_email, first_name,last_name, r_add, contact, household_s, lisiting_date, w_valid});
            }
        }catch (SQLException e){
            JOptionPane.showMessageDialog(this, "Error loading data" + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE );
        }     
    }*/
    
   
    
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SHOW_WHO_WORKER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SHOW_WHO_WORKER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SHOW_WHO_WORKER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SHOW_WHO_WORKER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Map<String, String> data = new HashMap<>();
                    data.put("FirstName", "");
                    data.put("LastName", "");
                    data.put("Address", "");
                    data.put("Email", "");
                    data.put("Contact", "");
                    data.put("Household", "");
                    data.put("Worker", "");
                    data.put("Suffix", "");
                    data.put("M_name", "");
                    data.put("Age", "");
                    data.put("B_date", "");
                    data.put("B_place", "");
                    data.put("Religion", "");
                    data.put("Citizenship", "");
                    data.put("Profession", "");
                    data.put("Enumer", "");
                    data.put("Build", "");
                    data.put("Housing", "");
                    data.put("Sex", "");
                    data.put("Status", "");
                    data.put("Attainment", "");
                    data.put("Date_Added", "");
                    data.put("Entry", "");

                    SHOW_WHO_WORKER v_UI = new SHOW_WHO_WORKER(username, Dbcon);
                new SHOW_WHO_WORKER(username, Dbcon).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PANEL_3;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel w_address;
    private javax.swing.JLabel w_age;
    private javax.swing.JLabel w_attainment;
    private javax.swing.JLabel w_birthdate;
    private javax.swing.JLabel w_cluster;
    private javax.swing.JLabel w_contact;
    private javax.swing.JLabel w_email;
    private javax.swing.JLabel w_full_name;
    private javax.swing.JLabel w_sex;
    private javax.swing.JLabel w_status;
    private javax.swing.JLabel w_user;
    // End of variables declaration//GEN-END:variables

    private static class JFrame extends Component {

        public JFrame() {
        }
    }
}
