/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sys_prototype_revised;

import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.awt.event.WindowEvent;
import java.awt.Component;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import javax.swing.table.DefaultTableModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowSorter;
import javax.swing.SwingUtilities;
import javax.swing.table.TableModel;
import static sys_prototype_revised.WORKER_DB_FOR_EDIT.record_table;

public class SHOW_DETAILS extends javax.swing.JFrame {

    private static String username;
    private static Connection Dbcon;

    private String sUrl = "jdbc:mysql://localhost:3306/user_" + username;
    private String sUser = "root";
    private String spass = "";
        
        
    private static PreparedStatement pst;
    private static ResultSet result;
    
    
    public SHOW_DETAILS(String username, Connection Dbcon, Map<String, String> data) {
        this.username = username;
        this.Dbcon = Dbcon;
        initComponents();
        
        r_first_name.setText(data.get("FirstName"));
        r_last_name.setText(data.get("LastName"));// Assuming r_last_name is your JTextField for Last Name
        r_address.setText(data.get("Address"));  // Assuming r_address is your JTextField for Address
        r_email_adress.setText(data.get("Email"));
        r_contact.setText(data.get("Contact"));
        r_household_serial.setText(data.get("Household"));
        inCharge.setText(data.get("Worker"));
        r_suffix.setText(data.get("Suffix"));
        r_middle_name.setText(data.get("M_name"));
        r_age.setText(data.get("Age"));
        r_birthdate.setText(data.get("B_date"));
        r_birthplace.setText(data.get("B_place"));
        r_religion.setText(data.get("Religion"));
        r_citizenship.setText(data.get("Citizenship"));
        r_profession.setText(data.get("Profession"));
        r_enumeration_serial.setText(data.get("Enumer"));
        r_building_serial.setText(data.get("Build"));
        r_housing_unit_serial.setText(data.get("Housing"));
        r_sex.setText(data.get("Sex"));
        r_status.setText(data.get("Status"));
        r_attainment.setText(data.get("Attainment"));
        r_listing.setText(data.get("Date_Added"));
        r_entry.setText(data.get("Entry"));
        
    }

    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PANEL_3 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        r_last_name = new javax.swing.JLabel();
        r_suffix = new javax.swing.JLabel();
        r_first_name = new javax.swing.JLabel();
        r_middle_name = new javax.swing.JLabel();
        r_sex = new javax.swing.JLabel();
        r_age = new javax.swing.JLabel();
        r_status = new javax.swing.JLabel();
        r_profession = new javax.swing.JLabel();
        r_birthdate = new javax.swing.JLabel();
        r_email_adress = new javax.swing.JLabel();
        r_religion = new javax.swing.JLabel();
        r_citizenship = new javax.swing.JLabel();
        r_attainment = new javax.swing.JLabel();
        r_contact = new javax.swing.JLabel();
        r_address = new javax.swing.JLabel();
        r_birthplace = new javax.swing.JLabel();
        r_enumeration_serial = new javax.swing.JLabel();
        r_building_serial = new javax.swing.JLabel();
        r_housing_unit_serial = new javax.swing.JLabel();
        r_household_serial = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        inCharge = new javax.swing.JLabel();
        r_listing = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        r_entry = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        PANEL_3.setBackground(new java.awt.Color(220, 227, 238));
        PANEL_3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PANEL_3.setForeground(new java.awt.Color(247, 247, 247));
        PANEL_3.setPreferredSize(new java.awt.Dimension(850, 500));

        jLabel28.setBackground(new java.awt.Color(247, 247, 247));
        jLabel28.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(40, 40, 40));
        jLabel28.setText("PERSONAL INFORMATION");
        jLabel28.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel28.setPreferredSize(new java.awt.Dimension(105, 20));

        jLabel29.setBackground(new java.awt.Color(0, 0, 0));
        jLabel29.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(26, 72, 98));
        jLabel29.setText("Last Name");

        jLabel30.setBackground(new java.awt.Color(247, 247, 247));
        jLabel30.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(26, 72, 98));
        jLabel30.setText("Suffix");

        jLabel31.setBackground(new java.awt.Color(247, 247, 247));
        jLabel31.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(26, 72, 98));
        jLabel31.setText("First Name");

        jLabel32.setBackground(new java.awt.Color(247, 247, 247));
        jLabel32.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(26, 72, 98));
        jLabel32.setText("Middle Name");

        jLabel33.setBackground(new java.awt.Color(247, 247, 247));
        jLabel33.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(26, 72, 98));
        jLabel33.setText("Sex");

        jLabel34.setBackground(new java.awt.Color(247, 247, 247));
        jLabel34.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(26, 72, 98));
        jLabel34.setText("Age");

        jLabel35.setBackground(new java.awt.Color(247, 247, 247));
        jLabel35.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(26, 72, 98));
        jLabel35.setText("Status");

        jLabel36.setBackground(new java.awt.Color(247, 247, 247));
        jLabel36.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(26, 72, 98));
        jLabel36.setText("Birthdate (mm/dd/yyyy) ");

        jLabel37.setBackground(new java.awt.Color(247, 247, 247));
        jLabel37.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(26, 72, 98));
        jLabel37.setText("Email Address");

        jLabel38.setBackground(new java.awt.Color(247, 247, 247));
        jLabel38.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(26, 72, 98));
        jLabel38.setText("Religion");

        jLabel39.setBackground(new java.awt.Color(247, 247, 247));
        jLabel39.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(26, 72, 98));
        jLabel39.setText("Citizenship");

        jLabel40.setBackground(new java.awt.Color(247, 247, 247));
        jLabel40.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(26, 72, 98));
        jLabel40.setText("Profession");

        jLabel41.setBackground(new java.awt.Color(247, 247, 247));
        jLabel41.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(26, 72, 98));
        jLabel41.setText("Residence Address");

        jLabel42.setBackground(new java.awt.Color(247, 247, 247));
        jLabel42.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(26, 72, 98));
        jLabel42.setText("Place Of Birth");

        jLabel43.setBackground(new java.awt.Color(247, 247, 247));
        jLabel43.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(26, 72, 98));
        jLabel43.setText("Contact No.");

        jLabel44.setBackground(new java.awt.Color(247, 247, 247));
        jLabel44.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(26, 72, 98));
        jLabel44.setText("Educational Attainment");

        jLabel45.setBackground(new java.awt.Color(220, 227, 238));
        jLabel45.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(40, 40, 40));
        jLabel45.setText("HOUSING INFORMATION");
        jLabel45.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel45.setPreferredSize(new java.awt.Dimension(105, 20));

        jLabel46.setBackground(new java.awt.Color(247, 247, 247));
        jLabel46.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(26, 72, 98));
        jLabel46.setText("Enumeration Serial Number");

        jLabel47.setBackground(new java.awt.Color(247, 247, 247));
        jLabel47.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(26, 72, 98));
        jLabel47.setText("Building Serial Number");

        jLabel48.setBackground(new java.awt.Color(247, 247, 247));
        jLabel48.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(26, 72, 98));
        jLabel48.setText("Housing Unit Serial Number");

        jLabel49.setBackground(new java.awt.Color(247, 247, 247));
        jLabel49.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(26, 72, 98));
        jLabel49.setText("Household Serial Number");

        jLabel51.setBackground(new java.awt.Color(247, 247, 247));
        jLabel51.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(26, 72, 98));
        jLabel51.setText("WORKER IN CHARGE");
        jLabel51.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel51.setPreferredSize(new java.awt.Dimension(105, 20));

        jButton2.setBackground(new java.awt.Color(76, 119, 102));
        jButton2.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(235, 230, 224));
        jButton2.setText("<");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(8, 17, 16));
        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(79, 41, 0));
        jLabel1.setText("RESPONDENT DETAILS");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(220, 227, 238), null, null));

        r_last_name.setBackground(new java.awt.Color(220, 227, 238));
        r_last_name.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        r_last_name.setForeground(new java.awt.Color(40, 40, 40));
        r_last_name.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        r_last_name.setPreferredSize(new java.awt.Dimension(105, 20));

        r_suffix.setBackground(new java.awt.Color(247, 247, 247));
        r_suffix.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        r_suffix.setForeground(new java.awt.Color(40, 40, 40));
        r_suffix.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        r_suffix.setPreferredSize(new java.awt.Dimension(105, 20));

        r_first_name.setBackground(new java.awt.Color(247, 247, 247));
        r_first_name.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        r_first_name.setForeground(new java.awt.Color(40, 40, 40));
        r_first_name.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        r_first_name.setPreferredSize(new java.awt.Dimension(105, 20));

        r_middle_name.setBackground(new java.awt.Color(247, 247, 247));
        r_middle_name.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        r_middle_name.setForeground(new java.awt.Color(40, 40, 40));
        r_middle_name.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        r_middle_name.setPreferredSize(new java.awt.Dimension(105, 20));

        r_sex.setBackground(new java.awt.Color(247, 247, 247));
        r_sex.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        r_sex.setForeground(new java.awt.Color(40, 40, 40));
        r_sex.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        r_sex.setPreferredSize(new java.awt.Dimension(105, 20));

        r_age.setBackground(new java.awt.Color(247, 247, 247));
        r_age.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        r_age.setForeground(new java.awt.Color(40, 40, 40));
        r_age.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        r_age.setPreferredSize(new java.awt.Dimension(105, 20));

        r_status.setBackground(new java.awt.Color(247, 247, 247));
        r_status.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        r_status.setForeground(new java.awt.Color(40, 40, 40));
        r_status.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        r_status.setPreferredSize(new java.awt.Dimension(105, 20));

        r_profession.setBackground(new java.awt.Color(247, 247, 247));
        r_profession.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        r_profession.setForeground(new java.awt.Color(40, 40, 40));
        r_profession.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        r_profession.setPreferredSize(new java.awt.Dimension(105, 20));

        r_birthdate.setBackground(new java.awt.Color(220, 227, 238));
        r_birthdate.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        r_birthdate.setForeground(new java.awt.Color(40, 40, 40));
        r_birthdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        r_birthdate.setPreferredSize(new java.awt.Dimension(105, 20));

        r_email_adress.setBackground(new java.awt.Color(220, 227, 238));
        r_email_adress.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        r_email_adress.setForeground(new java.awt.Color(40, 40, 40));
        r_email_adress.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        r_email_adress.setPreferredSize(new java.awt.Dimension(105, 20));

        r_religion.setBackground(new java.awt.Color(220, 227, 238));
        r_religion.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        r_religion.setForeground(new java.awt.Color(40, 40, 40));
        r_religion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        r_religion.setPreferredSize(new java.awt.Dimension(105, 20));

        r_citizenship.setBackground(new java.awt.Color(220, 227, 238));
        r_citizenship.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        r_citizenship.setForeground(new java.awt.Color(40, 40, 40));
        r_citizenship.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        r_citizenship.setPreferredSize(new java.awt.Dimension(105, 20));

        r_attainment.setBackground(new java.awt.Color(220, 227, 238));
        r_attainment.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        r_attainment.setForeground(new java.awt.Color(40, 40, 40));
        r_attainment.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        r_attainment.setPreferredSize(new java.awt.Dimension(105, 20));

        r_contact.setBackground(new java.awt.Color(220, 227, 238));
        r_contact.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        r_contact.setForeground(new java.awt.Color(40, 40, 40));
        r_contact.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        r_contact.setPreferredSize(new java.awt.Dimension(105, 20));

        r_address.setBackground(new java.awt.Color(220, 227, 238));
        r_address.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        r_address.setForeground(new java.awt.Color(40, 40, 40));
        r_address.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        r_address.setPreferredSize(new java.awt.Dimension(105, 20));

        r_birthplace.setBackground(new java.awt.Color(220, 227, 238));
        r_birthplace.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        r_birthplace.setForeground(new java.awt.Color(40, 40, 40));
        r_birthplace.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        r_birthplace.setPreferredSize(new java.awt.Dimension(105, 20));

        r_enumeration_serial.setBackground(new java.awt.Color(247, 247, 247));
        r_enumeration_serial.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        r_enumeration_serial.setForeground(new java.awt.Color(40, 40, 40));
        r_enumeration_serial.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        r_enumeration_serial.setPreferredSize(new java.awt.Dimension(105, 20));

        r_building_serial.setBackground(new java.awt.Color(247, 247, 247));
        r_building_serial.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        r_building_serial.setForeground(new java.awt.Color(40, 40, 40));
        r_building_serial.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        r_building_serial.setPreferredSize(new java.awt.Dimension(105, 20));

        r_housing_unit_serial.setBackground(new java.awt.Color(247, 247, 247));
        r_housing_unit_serial.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        r_housing_unit_serial.setForeground(new java.awt.Color(40, 40, 40));
        r_housing_unit_serial.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        r_housing_unit_serial.setPreferredSize(new java.awt.Dimension(105, 20));

        r_household_serial.setBackground(new java.awt.Color(247, 247, 247));
        r_household_serial.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        r_household_serial.setForeground(new java.awt.Color(40, 40, 40));
        r_household_serial.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        r_household_serial.setPreferredSize(new java.awt.Dimension(105, 20));

        jLabel50.setBackground(new java.awt.Color(247, 247, 247));
        jLabel50.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(26, 72, 98));
        jLabel50.setText("Date Listed");

        inCharge.setBackground(new java.awt.Color(220, 227, 238));
        inCharge.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        inCharge.setForeground(new java.awt.Color(40, 40, 40));
        inCharge.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        inCharge.setPreferredSize(new java.awt.Dimension(105, 20));

        r_listing.setBackground(new java.awt.Color(247, 247, 247));
        r_listing.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        r_listing.setForeground(new java.awt.Color(40, 40, 40));
        r_listing.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        r_listing.setPreferredSize(new java.awt.Dimension(105, 20));

        jLabel52.setBackground(new java.awt.Color(247, 247, 247));
        jLabel52.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(26, 72, 98));
        jLabel52.setText("ENTRY STATUS");
        jLabel52.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel52.setPreferredSize(new java.awt.Dimension(105, 20));

        r_entry.setBackground(new java.awt.Color(220, 227, 238));
        r_entry.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        r_entry.setForeground(new java.awt.Color(40, 40, 40));
        r_entry.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        r_entry.setPreferredSize(new java.awt.Dimension(105, 20));

        javax.swing.GroupLayout PANEL_3Layout = new javax.swing.GroupLayout(PANEL_3);
        PANEL_3.setLayout(PANEL_3Layout);
        PANEL_3Layout.setHorizontalGroup(
            PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_3Layout.createSequentialGroup()
                .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PANEL_3Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel1)
                        .addGap(144, 144, 144)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PANEL_3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(PANEL_3Layout.createSequentialGroup()
                                    .addComponent(jLabel37)
                                    .addGap(358, 358, 358)
                                    .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel35)
                                        .addGroup(PANEL_3Layout.createSequentialGroup()
                                            .addGap(70, 70, 70)
                                            .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel33)
                                                .addComponent(r_sex, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                                        .addComponent(r_status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(PANEL_3Layout.createSequentialGroup()
                                    .addGap(170, 170, 170)
                                    .addComponent(r_first_name, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                    .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANEL_3Layout.createSequentialGroup()
                                                .addComponent(r_citizenship, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(137, 137, 137))
                                            .addGroup(PANEL_3Layout.createSequentialGroup()
                                                .addComponent(jLabel40)
                                                .addGap(66, 66, 66)
                                                .addComponent(jLabel38))
                                            .addComponent(jLabel39)
                                            .addGroup(PANEL_3Layout.createSequentialGroup()
                                                .addComponent(r_middle_name, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(36, 36, 36)
                                                .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel34)
                                                    .addComponent(r_suffix, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(r_age, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(PANEL_3Layout.createSequentialGroup()
                                            .addComponent(jLabel32)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel30)
                                            .addGap(67, 67, 67)))))
                            .addGroup(PANEL_3Layout.createSequentialGroup()
                                .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(r_last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel36)
                                    .addComponent(r_birthdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel42)
                                    .addComponent(r_birthplace, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(PANEL_3Layout.createSequentialGroup()
                                    .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel41)
                                        .addComponent(r_address, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(r_household_serial, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(PANEL_3Layout.createSequentialGroup()
                                            .addComponent(r_attainment, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(inCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(PANEL_3Layout.createSequentialGroup()
                                            .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(r_email_adress, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel44))
                                            .addGap(18, 18, 18)
                                            .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel43)
                                                .addComponent(r_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(r_entry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(PANEL_3Layout.createSequentialGroup()
                                            .addComponent(r_profession, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(r_religion, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PANEL_3Layout.createSequentialGroup()
                                    .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(r_enumeration_serial, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel49))
                                    .addGap(30, 30, 30)
                                    .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel48)
                                        .addComponent(r_housing_unit_serial, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(PANEL_3Layout.createSequentialGroup()
                                            .addComponent(r_building_serial, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(80, 80, 80)
                                            .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel50)
                                                .addComponent(r_listing, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PANEL_3Layout.createSequentialGroup()
                                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel47)))))
                    .addGroup(PANEL_3Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        PANEL_3Layout.setVerticalGroup(
            PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PANEL_3Layout.createSequentialGroup()
                        .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel32)
                                .addComponent(jLabel30))
                            .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(r_middle_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(r_first_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(r_last_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(r_suffix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36)
                            .addComponent(jLabel34)
                            .addComponent(jLabel33)
                            .addComponent(jLabel42))
                        .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(r_birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(r_birthplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(r_age, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANEL_3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(r_sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PANEL_3Layout.createSequentialGroup()
                        .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel41)
                            .addComponent(jLabel39))
                        .addGap(0, 0, 0)
                        .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(r_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r_citizenship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r_status, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel35))
                .addGap(18, 18, 18)
                .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38)
                    .addComponent(jLabel40)
                    .addComponent(jLabel43)
                    .addComponent(jLabel37))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PANEL_3Layout.createSequentialGroup()
                        .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(r_email_adress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(r_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(r_profession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANEL_3Layout.createSequentialGroup()
                        .addComponent(r_religion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0)
                .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r_attainment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r_entry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inCharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANEL_3Layout.createSequentialGroup()
                        .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel46)
                            .addComponent(jLabel47)
                            .addComponent(jLabel50))
                        .addGap(2, 2, 2)
                        .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(r_building_serial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r_enumeration_serial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(r_listing, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(jLabel48))
                .addGap(0, 0, 0)
                .addGroup(PANEL_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r_household_serial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r_housing_unit_serial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PANEL_3, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(PANEL_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        close();
        WORKER_DB_FOR_EDIT main_L = new WORKER_DB_FOR_EDIT(username, Dbcon);
        main_L.setVisible(true);
        main_L.pack();
        main_L.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void updateRespondent(Connection Dbcon, String worker_in_charge, String l_name, String suffix, String f_name, String m_name, 
        String sex, String age, String status, String birthdate, String birthplace, String religion, 
        String citizenship, String profession, String address, String email, String contact_no, String attainment, 
        String enumeration_serial, String building_serial, String housing_unit_serial, 
        String household_serial) throws SQLException {

        String query = "UPDATE res_info SET respondent_email = ?, f_name = ?, l_name = ?, address = ?, contact_no = ?," + 
                       "household_serial= ?, worker_incharge = ?, suffix = ?, m_name = ?, r_sex = ?," + 
                       "r_status = ?, r_age = ?, r_birthdate = ?, r_birthplace = ?, r_religion = ?," + 
                       "r_citizenship = ?, r_profession = ?, r_attainment = ?, enumeration_serial = ?," + 
                       "building_serial = ?, housing_unit_serial = ?, date_listed = NOW() WHERE respondent_email = ?";
    
        try (PreparedStatement insertaddRespondentStmt = Dbcon.prepareStatement(query)) {
            insertaddRespondentStmt.setString(1, email);
            insertaddRespondentStmt.setString(2, f_name);
            insertaddRespondentStmt.setString(3, l_name);
            insertaddRespondentStmt.setString(4, address);
            insertaddRespondentStmt.setString(5, contact_no);
            insertaddRespondentStmt.setString(6, household_serial);
            insertaddRespondentStmt.setString(7, worker_in_charge);
            insertaddRespondentStmt.setString(8, suffix);
            insertaddRespondentStmt.setString(9, m_name);
            insertaddRespondentStmt.setString(10, sex);
            insertaddRespondentStmt.setString(11, status);
            insertaddRespondentStmt.setString(12, age);
            insertaddRespondentStmt.setString(13, birthdate);
            insertaddRespondentStmt.setString(14, birthplace);
            insertaddRespondentStmt.setString(15, religion);
            insertaddRespondentStmt.setString(16, citizenship);
            insertaddRespondentStmt.setString(17, profession);
            insertaddRespondentStmt.setString(18, attainment);
            insertaddRespondentStmt.setString(19, enumeration_serial);
            insertaddRespondentStmt.setString(20, building_serial);
            insertaddRespondentStmt.setString(21, housing_unit_serial);
            insertaddRespondentStmt.setString(22, email);
            insertaddRespondentStmt.executeUpdate();
        }
    }
    
    
    public void UpdateDB(){
        
        String sUrl = "jdbc:mysql://localhost:3306/user_" + username;
        String sUser = "root";
        String spass = "";
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Dbcon = DriverManager.getConnection(sUrl, sUser, spass);
            pst = Dbcon.prepareStatement("SELECT * FROM res_info ORDER BY time_created DESC");
            
            result = pst.executeQuery();
            ResultSetMetaData resultData = result.getMetaData();
            
            int q = resultData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)record_table.getModel();
            RecordTable.setRowCount(0);
            
            while(result.next()){
                Vector columnData = new Vector();
                
                for(int r = 1; r <= q; r++){
                    columnData.add(result.getString("respondent_email"));
                    columnData.add(result.getString("f_name"));
                    columnData.add(result.getString("l_name"));
                    columnData.add(result.getString("address"));
                    columnData.add(result.getString("contact_no"));
                    columnData.add(result.getString("household_serial"));
                    columnData.add(result.getString("date_listed"));
                    columnData.add(result.getString("validation"));
                    
                }
                RecordTable.addRow(columnData);
            }
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    public void showTableDb()throws SQLException{
        if(Dbcon == null || Dbcon.isClosed()){
            System.out.println("CHECK DATABASE CONNECTION");
            return;
        }
        String query = "SELECT * FROM res_info ORDER BY time_created DESC";
        try(PreparedStatement stmt = Dbcon.prepareStatement(query)){
            
            ResultSet result = stmt.executeQuery();
            
            DefaultTableModel RecordTable = (DefaultTableModel)record_table.getModel();
            RecordTable.setRowCount(0);
            
            
            
            while(result.next()){
                /*StringBuilder details = new StringBuilder();
                ResultSetMetaData metadata = result.getMetaData();
                int columnCount = metadata.getColumnCount();
                */
                String r_email = result.getString("respondent_email");
                String first_name = result.getString("f_name");
                String last_name = result.getString("l_name");
                String r_add = result.getString("address");
                String contact = result.getString("contact_no");
                String household_s = result.getString("household_serial");
                String lisiting_date = result.getString("date_listed");
                String w_valid = result.getString("validation");
                
                RecordTable.addRow(new Object[]{r_email, first_name,last_name, r_add, contact, household_s, lisiting_date, w_valid});
            }
        }catch (SQLException e){
            JOptionPane.showMessageDialog(this, "Error loading data" + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE );
        }     
    }
    
   
    
   
    private void showError(String message) {
         JOptionPane.showMessageDialog(this, message,"Error", JOptionPane.ERROR_MESSAGE);

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SHOW_DETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SHOW_DETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SHOW_DETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SHOW_DETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Map<String, String> data = new HashMap<>();
                    data.put("FirstName", "");
                    data.put("LastName", "");
                    data.put("Address", "");
                    data.put("Email", "");
                    data.put("Contact", "");
                    data.put("Household", "");
                    data.put("Worker", "");
                    data.put("Suffix", "");
                    data.put("M_name", "");
                    data.put("Age", "");
                    data.put("B_date", "");
                    data.put("B_place", "");
                    data.put("Religion", "");
                    data.put("Citizenship", "");
                    data.put("Profession", "");
                    data.put("Enumer", "");
                    data.put("Build", "");
                    data.put("Housing", "");
                    data.put("Sex", "");
                    data.put("Status", "");
                    data.put("Attainment", "");
                    data.put("Date_Added", "");
                    data.put("Entry", "");

                    SHOW_DETAILS v_UI = new SHOW_DETAILS(username, Dbcon, data);
                new SHOW_DETAILS(username, Dbcon, data).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PANEL_3;
    private javax.swing.JLabel inCharge;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel r_address;
    private javax.swing.JLabel r_age;
    private javax.swing.JLabel r_attainment;
    private javax.swing.JLabel r_birthdate;
    private javax.swing.JLabel r_birthplace;
    private javax.swing.JLabel r_building_serial;
    private javax.swing.JLabel r_citizenship;
    private javax.swing.JLabel r_contact;
    private javax.swing.JLabel r_email_adress;
    private javax.swing.JLabel r_entry;
    private javax.swing.JLabel r_enumeration_serial;
    private javax.swing.JLabel r_first_name;
    private javax.swing.JLabel r_household_serial;
    private javax.swing.JLabel r_housing_unit_serial;
    private javax.swing.JLabel r_last_name;
    private javax.swing.JLabel r_listing;
    private javax.swing.JLabel r_middle_name;
    private javax.swing.JLabel r_profession;
    private javax.swing.JLabel r_religion;
    private javax.swing.JLabel r_sex;
    private javax.swing.JLabel r_status;
    private javax.swing.JLabel r_suffix;
    // End of variables declaration//GEN-END:variables
}
