/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sys_prototype_revised;

import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.awt.event.WindowEvent;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;

/**
 *
 * @author Rodulfo R. Lopez
 */
public class validation_process_PROTO extends javax.swing.JFrame {

    private String username;
    private Connection Dbcon;
    
    public validation_process_PROTO(String username, Connection Dbcon) {
        
        this.username = username;
        this.Dbcon = Dbcon;
        initComponents();

    }
    
    private validation_process_PROTO() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        input_v_code = new javax.swing.JTextField();
        validate_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(220, 227, 238));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 125));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(40, 40, 40));
        jLabel1.setText("ENTER YOUR WORKER CODE TO VALIDATE ALL DATA");
        jLabel1.setPreferredSize(new java.awt.Dimension(305, 15));

        input_v_code.setBackground(new java.awt.Color(247, 247, 247));
        input_v_code.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        input_v_code.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        input_v_code.setPreferredSize(new java.awt.Dimension(80, 20));
        input_v_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_v_codeActionPerformed(evt);
            }
        });

        validate_btn.setBackground(new java.awt.Color(247, 247, 247));
        validate_btn.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        validate_btn.setForeground(new java.awt.Color(40, 40, 40));
        validate_btn.setText("VALIDATE DATA");
        validate_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        validate_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validate_btnActionPerformed(evt);
            }
        });

        back_btn.setBackground(new java.awt.Color(76, 119, 102));
        back_btn.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        back_btn.setForeground(new java.awt.Color(235, 230, 224));
        back_btn.setText("<");
        back_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back_btn.setPreferredSize(new java.awt.Dimension(30, 30));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(input_v_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(validate_btn)
                        .addGap(150, 150, 150))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(input_v_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(validate_btn)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void input_v_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_v_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_v_codeActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
            close();
            WORKER_DB_FOR_EDIT w_db = new WORKER_DB_FOR_EDIT(username, Dbcon);
            w_db.setVisible(true);
            w_db.pack();
            w_db.setLocationRelativeTo(null);
            this.dispose();
        
    }//GEN-LAST:event_back_btnActionPerformed

    private void validate_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validate_btnActionPerformed
        String input_code = input_v_code.getText();
        if(input_code.isEmpty()){
            JOptionPane.showMessageDialog(this, "ENTER YOUR CODE PLEASE");
            return;
        }
        
        int user_input_code;
        try{
            user_input_code = Integer.parseInt(input_code);
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "INVALID NUMBER FORMAT");
            return;
        }
        
        String SUrl, SUser, Spass;
        SUrl = "jdbc:mysql://localhost:3306/user_" + username;
        SUser = "root";
        Spass = "";
        
        try(Connection dbCON = DriverManager.getConnection(SUrl, SUser, Spass)){
            String checkerQuery = "SELECT COUNT(*) FROM census_system_db.login_details WHERE validation_code = ?";
            try(PreparedStatement checkSTMT = dbCON.prepareStatement(checkerQuery)){
                checkSTMT.setInt(1, user_input_code);
                ResultSet result = checkSTMT.executeQuery();
                result.next();
                int counter = result.getInt(1);
                
                if(counter > 0){
                    String updaterQuery = "UPDATE user_" + username 
                            +".res_info SET validation = 'VALIDATED' WHERE validation = 'NOT YET VALIDATED'";
                    try(PreparedStatement updateSTMT = dbCON.prepareStatement(updaterQuery )){
                        int rowsUpdated = updateSTMT.executeUpdate();
                        if(rowsUpdated > 0){
                            JOptionPane.showMessageDialog(this, "STATUS UPDATED");
                        }else{
                            JOptionPane.showMessageDialog(this, "NOTHING TO VALIDATE");
                        }
                    }
                        close();
                        WORKER_DB_FOR_EDIT w_db = new WORKER_DB_FOR_EDIT(username, Dbcon);
                        w_db.setVisible(true);
                        w_db.pack();
                        w_db.setLocationRelativeTo(null);
            this.dispose();
                }else{
                    JOptionPane.showMessageDialog(this, "CODE NOT FOUND IN  THE RECORDS");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(validation_process_PROTO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_validate_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(validation_process_PROTO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(validation_process_PROTO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(validation_process_PROTO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(validation_process_PROTO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new validation_process_PROTO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JTextField input_v_code;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton validate_btn;
    // End of variables declaration//GEN-END:variables
}
